micronaut:
  application:
    name: outageBG
  metrics:
    enabled: false
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
datasources:
  default:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/outageBG
    dbType: postgres
    dialect: POSTGRES
    username: postgres
    password: postgres
jpa:
  default:
    entity-scan:
      packages: 'com.outage'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
